config/routes.rb
Rails.application.routes.draw do
  resources :posts, only: [:create, :new] do
    resources :comments, only: [:create, :new], as: 'comments' do
      post "likes", to: 'likes#comment_likes_create'
      delete "likes", to: 'likes#comment_likes_destroy'
    end
    post "likes", to: 'likes#post_likes_create'
    delete "likes", to: 'likes#post_likes_destroy'
  end
  devise_for :users
  root "site#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  has_many :likes, as: :likeable, dependent: :destroy
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :likeable, polymorphic: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, as: :likeable, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
  has_many :likes
  has_many :comments

  validates :username, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_params, if: :devise_controller?

  protected

    def configure_permitted_params
      devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
  end

  def create
    @post = Post.find(params[:post_id])
    comment = Comment.new(comment_params)
    comment.post = @post
    comment.user = current_user

    if comment.save
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

    def comment_params
      params.require(:comment).permit(:body)
    end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  before_action :get_comment
  before_action :get_post

  def post_likes_create
    @post.likes.create(user_id: current_user.id)
  end

  def post_likes_destroy
    @post.likes.where(user_id: current_user.id).delete_all
  end

  def comment_likes_create
    @comment.likes.create(user_id: current_user.id)
  end

  def comment_likes_destroy
    @comment.likes.where(user_id: current_user.id).delete_all
  end

  private
  def get_post
    @post = Post.find_by(id: params[:post_id])
  end
  def get_comment
    @comment = Comment.find_by(id: params[:comment_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id

    if @post.valid?
      @post.save
      flash[:notice] = "Your post has been just created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  private
    def post_params
      params.require(:post).permit(:body)
    end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def index
    @posts = Post.all.order("created_at DESC")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
  def hasLikedComment(comment)
    if current_user
      if current_user.likes.find_by(likeable_id: comment.id, likeable_type: "Comment")
        true
      else
        false
      end
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  def hasLikedPost(post)
    if current_user
      if current_user.likes.find_by(likeable_id: post.id, likeable_type: "Post")
        true
      else
        false
      end
    end
  end
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/comments/_form.html.erb
<%= form_with model: Comment.new, url: post_comments_path(post), class: "comment-form" do |f| %>
  <%= f.text_field :body %>
  <%= f.submit :send %>
<% end %>

app/views/comments/_list.html.erb
 <% post.comments.sort.reverse.each do |comment|%>
  <div class="comment">
    <div>
      <span> <%= comment.user.username %>: </span>
      <%= comment.body%> 
    </div>

    <%= turbo_frame_tag "comment-likes" do %>
     <div class="post-likes" >
        <% if hasLikedComment(comment) %>
          <%= button_to "", post_comment_likes_path(post, comment), params: {likeable_type: "Comment"}, class: "post-actions-unlike", method: :delete%>
        <%else%>
          <%= button_to "", post_comment_likes_path(post, comment), params: {likeable_type: "Comment"}, class: "post-actions-like" %>
        <% end %>
      </div>
    <% end %>
  
  </div>
<%end%>

app/views/comments/create.turbo_stream.erb
<%= turbo_stream.update "post-comments-count" do %>
  <%= pluralize(@post.comments.count, "comment") %>
<%end%>

<%= turbo_stream.update "comment-form" do %>
  <%= render partial: "comments/form", locals: { post: @post } %>
<% end %> 

<%= turbo_stream.update "post-comments-list-#{@post.id}" do %>
  <%= render partial: "comments/list", locals: {post: @post}%>
<%end %>

app/views/comments/new.turbo_stream.erb
<%= turbo_stream.update "comment-form" do %>
  <%= render partial: "comments/form", locals: { post: @post } %>
<% end %> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Instaclone</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flash" %>
    <div class="container-fluid">
      <%= yield %>
    </div>
    
  </body>
</html>

app/views/likes/comment_likes_create.html.erb
<%= turbo_frame_tag "comment-likes" do %>
  <%= button_to "", post_comment_likes_path(@post, @comment), params: {likeable_type: "Comment"}, class: "post-actions-unlike", method: :delete%>
<%end%>

app/views/likes/comment_likes_destroy.html.erb
<%= turbo_frame_tag "comment-likes" do %>
  <%= button_to "", post_comment_likes_path(@post, @comment), params: {likeable_type: "Comment"}, class: "post-actions-like" %>
<% end %>

app/views/likes/post_likes_create.html.erb
<%= turbo_frame_tag "post-likes" do %>
  <%= button_to "", post_likes_path(@post), params: {likeable_type: "Post"}, class: "post-actions-unlike" , method: :delete%>
<% end %>

app/views/likes/post_likes_destroy.html.erb
<%= turbo_frame_tag "post-likes" do %>
  <%= button_to "", post_likes_path(@post), params: {likeable_type: "Post"}, class: "post-actions-like" %>
<% end %>

app/views/posts/_post.html.erb
<div class="post" id=<%= "post-#{post.id}"%>>
  <div class="post-author">
    <div class="avatar avatar-<%= rand(1..27) %>"></div>
    <div><%= post.user.email %></div>
  </div>
  <div class="post-body">
    <span><%= post.body %></span>
  </div>

  <div class="post-actions" >
    <div class="post-likes">
    <%= turbo_frame_tag "post-likes" do %>
      <% if hasLikedPost(post) %>
          <%= button_to "", post_likes_path(post), params: {likeable_type: "Post"}, class: "post-actions-unlike" , method: :delete%>
      <%else%>
          <%= button_to "", post_likes_path(post), params: {likeable_type: "Post"}, class: "post-actions-like" %>
      <% end %>
    <% end %>
    </div>
    <div>
      <div class="post-actions-comments" id="post-comments-count"> <%= pluralize(post.comments.count, "comment") %> </div>
    </div>
  </div>

  <div class="post-comments">
    <div id="comment-form">
      <%= render partial: "comments/form", locals: {post: post}%>
    </div>

    <div id="post-comments-list-<%= post.id%>">
      <%= render partial: "comments/list", locals: {post: post}%>
    </div>
  </div>
</div>

app/views/posts/create.turbo_stream.erb
<%= turbo_stream.prepend "posts" do %>
  <%= render partial: "post", locals: {post: @post} %>
<% end %>

app/views/posts/new.html.erb
<%= turbo_frame_tag "post-form" do %>
  <%= form_with model: @post do |f|%>
    <%= f.text_field :body%>
    <%= f.submit :send %>
  <% end %>
<% end %>

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
  <div class="alert alert-success mt-4" role="alert">
    <%= flash[:notice] %>
  </div>
<% end %>
<% if flash[:alert] %>
  <div class="alert alert-warning mt-4" role="alert">
    <%= flash[:alert] %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to "Instaclone", root_path, class: "navbar-brand" %> 
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav w-100 d-flex align-items-center justify-content-between">
        <div class="d-flex gap-2 align-items-center">
          <li class="nav-item">
            <%= link_to "Home", root_path, class: "nav-link" %> 
          </li>
          <%= turbo_frame_tag "post-form" do %>
            <li class="nav-item">
              <%= link_to "New post", new_post_path, class: "nav-link" %> 
            </li>
          <% end %>
        </div>

        <div class="d-flex gap-3">
          <% if user_signed_in? %>
            <%= link_to "Sign out", destroy_user_session_path, data: {turbo_method: :delete}%>
          <% else %>
            <%= link_to "Sign in", new_user_session_path%>
            <%= link_to "Sign up", new_user_registration_path%>
          <% end %>
        </div>
      </ul>
    </div>
  </div>
</nav>

app/views/site/index.html.erb
<div>
  <h1> <%= current_user ? "Welcome #{current_user.username}"  : "Log in to see the posts"  %></h1>
</div>

<div id="posts">
  <%= render @posts if current_user %>
</div>